server:
  port: 8081
spring:
  application:
    name: feiyue-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC
    username: root
    password: root
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  rabbitmq:
    host: 192.168.232.139
    port: 5672
    username: feiyue
    password: feiyue
    virtual-host: /feiyue
    template:
      exchange: FEIYUE.ITEM.EXCHANGE # 配置默认交换机
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5     #5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 15 #10秒不发送就过期
mybatis:
  type-aliases-package: io.feiyue.item.pojo
