server:
  port: 8085
spring:
  application:
    name: feiyue-user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.232.139
  rabbitmq:
    host: 192.168.232.139
    username: feiyue
    password: feiyue
    virtual-host: /feiyue
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: io.feiyue.user.pojo