server:
  port: 8084
spring:
  application:
    name: feiyue-goods-web
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.232.139
    port: 5672
    username: feiyue
    password: feiyue
    virtual-host: /feiyue
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15