server:
  port: 8088
spring:
  application:
    name: feiyue-cart
  redis:
    host: 192.168.232.139
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
feiyue:
  jwt:
    pubKeyPath: D:\\users\\rsa\\rsa.pub # 公钥地址
    cookieName: FEIYUE_TOKEN
